openapi: "3.0.0"

info:
  title: "ITSM Calls - Baloise SIAM-SID"
  version: "0.1"
servers:
  - url: /itsm/v0.1

paths:
  /change:
    post:
      summary: "Update Standard Change"
      description: "Update a standard change"
      operationId: itsm.calls_change.update_change
      responses:
        200:
          description: "Creation succeeded"
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/update_change_response"
        404:
          description: "Ticket not exist"
        500:
          description: "Server error"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/update_change"
      security:
        - bearer_auth: []
components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
      x-bearerInfoFunc: auth.bearer_auth
  schemas:
    update_change:
      type: object
      properties:
        ticketno:
          type: string
          pattern: "^CH-[0-9]{7}$"
          example: "CH-0032554"
        status:
          type: string
          enum:
            - CH_CLD
            - CH_IMPF
            - CH_CHGF
        description:
          type: string
          example: "failed and not complete"
        taskname:
          type: string
          example: "Cloning"
        changeOwnerGroup:
          type: string
          nullable: true
          example: "HCL-DCOps"
      example: >
        {
          "ticketno": "CH-0000016",
          "status": "CH_IMPF",
          "description": "Error on playbook need investigated !",
          "taskname": "Cloning",
          "changeOwnerGroup": "HCL-DCOps"
        }

    update_change_response:
      type: object
      properties:
        status:
          type: string
        ticketno:
          type: string
