openapi: "3.0.0"

info:
  title: "ITSM Calls - Baloise SIAM-SID"
  version: "0.1"
servers:
  - url: /itsm/v0.1

paths:
  /change:
    post:
      summary: "Update Standard Change"
      description: "Update a standard change"
      operationId: itsm.calls_change.update_change
      responses:
        200:
          description: "Creation succeeded"
          content:
            application/json:
              schema:
                $ref: "#components/schemas/update_change_response"
      requestBody:
        content:
          application/json:
            schema:
              $ref: "#components/schemas/update_change"
      security:
        - bearer_auth: []
components:
  securitySchemes:
    bearer_auth:
      type: http
      scheme: bearer
      x-bearerInfoFunc: auth.bearer_auth
  schemas:
    update_change:
      type: object
      properties:
        changeno:
          type: string
          pattern: "^CH-[0-9]{7}$"
          example: "CH-0032554"
        status:
          type: string
          enum:
            - CH_CLD
            - CH_IMPF
        taskname:
          type: string
          example: "Task #5"
        description:
          type: string
          example: "failed and not complete"
        supportgroup:
          type: string
          pattern: "[^@ \t\r\n]+@[^@ \t\r\n]+\\.[^@ \t\r\n]+"
          example: "group.foo@foo.com"
      example: >
        {
          "changeno": "CH-0000016",
          "status": "CH_IMPF",
          "taskname": "Task #7",
          "description": "Error on playbook need investigated !",
          "supportgroup": "group.foo@foo.com"
        }

    update_change_response:
      type: object
      properties:
        changestatus:
          type: string
        changeno:
          type: string
