openapi: "3.0.0"

info:
  title: Baloise Private OIM API
  version: "0.1"
servers:
  - url: /private/v0.1

paths:
  /order/createminimal:
    post:
      summary: "manually creates a minimal order" 
      description: | 
        This is a private method only used for testing internally. Normally orders are created when
        a resource is ordered. This should never be called directly by customers.
      operationId: api.calls_status.create_minimal_order
      tags:
        - orders
      responses:
        '201':
          description: "order created successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  order_id:
                    type: integer
                    description: The ID of the newly created ordered.
                    example: 23596839285
        '400':
          description: Invalid requestBody
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
      requestBody:
        required: false
        content:
          application/json:
            schema:
              x-body-name: orderinfo
              type: object
              properties:
                order_id:
                  type: integer
                  example: 5847646563843
                requester_username:
                  $ref: "#/components/schemas/od.username"

  /status/create:
    post:
      summary: Create a new status entry
      operationId: api.calls_status.create_status
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Status"
      responses:
        '201':
          description: "status created successfully"
          content:
            application/json:
              schema:
                type: object
                properties:
                  statusid:
                    type: integer
                    description: The ID of the newly created status
                    example: 23596839285
        '400':
          description: "Invalid requestBody"

components:
  responses:
    NotFound:
      description: The specified resource was not found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
    Unauthorized:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'

  schemas:
    Error:
      type: object
      properties:
        code:
          type: string
        message:
          type: string
      required:
        - code
        - message
    Status: 
      type: object
      required:
        - state
        - system
        - orderid
      properties:
        statusid:
          type: integer
          example: 42
        state:
          type: string
          enum:
            - 'NEW'
            - 'VERIFIED'
            - 'BE_PROCESSING'
            - 'BE_DONE'
            - 'BE_FAIL'
            - 'TESTING'
            - 'TEST_FAIL'
            - 'TEST_SUCCESS'
            - 'CMDB_DONE'
            - 'DONE'
          example: 'NEW'
        since:
          type: integer
          description: timestamp
          example: 123945857
        system:
          type: string
          enum:
            - 'ORCHESTRA'
            - 'OURCLOUD'
        orderid:
          type: integer
          description: ID of the order this status belongs to
          example: 384738477583
        payload:
          type: string
          description: Freeform text to contain additional status info
    od.username:
      type: string
      pattern: "^[bB][0-9]{6}$"
      example: "b000000"
