openapi: "3.0.0"

info:
  title: "OIM API"
  version: "0.2"
  description: |
    These endpoints are used for developent testing purposes. DO NOT call them unless
    you're certain that that you know what they do. The name isn't always indicative
    of what's inside these calls!
servers:
  - url: /oim/v0.2

paths:
  /test/gettoken:
    get:
      summary: get an auth token from ocBackend
      description: Retrieves a token either from cache or from the live ocBackend
      operationId: orderitems.demo.tokendemo
      responses:
        200:
          description: token response
          content:
            text/plain:
              schema:
                type: string

